### PR TITLE
HOUSNAV-53: Add PR template

### PR DESCRIPTION
**Pull request by wardm89**
[HOUSNAV-53](https://hous-bssb.atlassian.net/jira/software/c/projects/HOUSNAV/boards/3?selectedIssue=HOUSNAV-53)

## Overview & Purpose

Add PR template to reduce time writing PR descriptions and standardizing PRs enabling faster testing times and "future selves" looking at old PRs to see what changed.

## Summary of Changes

- Adding template to the `.github` directory

### CODE REVIEW

**Review by nicholaslyon-dt — APPROVED** [review]

**Review by nicholaslyon-dt — CHANGES_REQUESTED** [review]
Actually, can we get the ticket helper to have a default that matches our JIRA? Make it quicker to fill in?

`[HOUSNAV-10](https://hous-bssb.atlassian.net/browse/HOUSNAV-10)`

**Comment by nicholaslyon-dt** [comment]
Ooo we should also add a question for Testing Notes.

**Comment by wardm89** [comment]
> Ooo we should also add a question for Testing Notes.

The `Notes and Resources` is there any testing notes can go. However I'm fine with breaking that out into a separate section if we really want that additional distinction.

**Review by laurenrevere — APPROVED** [review]
Looks good to me! I do think we could make this even shorter if we wanted. 

I don't think we need a specific testing section, but if we did add one I'd combine side effects with notes and add testing at the end.


Update: but @nicholaslyon-dt's format shown here probably will work well as well. https://github.com/bcgov/House-Innovations-HOUSNAV/pull/25

**Comment by nicholaslyon-dt** [comment]
> > Ooo we should also add a question for Testing Notes.
> 
> The `Notes and Resources` is there any testing notes can go. However I'm fine with breaking that out into a separate section if we really want that additional distinction.

I would appreciate breaking it out as I tend to always need to list testing steps and those would just overtake any notes I add. I would think separate is easier to read and write:

Screenshot 2024-06-05 at 1 11 31 PM

Than together:

Screenshot 2024-06-05 at 1 12 19 PM

Thoughts y'all?

**Comment by wardm89** [comment]
I'm good with this as it stands right now. If we come up with any other changes down the line we can update it then.

One thing to note is all the sections aren't necessary so if one doesn't apply just delete it.

**Review by nicholaslyon-dt — APPROVED** [review]

**Pull request merged**
