### PR TITLE
HOUSNAV-71: BC DT 9.10.14

### PR DESCRIPTION
**Pull request by wardm89**
[HOUSNAV-71](https://hous-bssb.atlassian.net/browse/HOUSNAV-71)

## Overview & Purpose

Add building code json data for 9.10.14.1-4

## Summary of Changes

- Updates Building code json adding 9.10.14.1-4
- Minor CSS adjustments
- Added `ImageModalType` and accompanying functions to handle a more detailed image in the building code 
Screenshot 2024-07-09 at 11 29 46 AM
Screenshot 2024-07-09 at 11 29 56 AM

## Side Effects

- After removing the `section` and `div` from wrapping the list items the numbers and letters are now `outside` of the highlighted section. There is no "right or wrong" for this since there isn't a design for highlighting a sentence or clause. 
    - If we did want the number within the highlight, the only way I see how would be to move the numbers to "inside" the list item so it's indented rather than to the left outside list item's container.
Screenshot 2024-07-09 at 11 58 37 AM
Screenshot 2024-07-09 at 11 57 49 AM

## Testing

- Verify glossary links, tooltips and building code references
- Some of the pdf links reference the Article for the sentence when a specific sentence is linked due to not being able to reference a named destination for a specific sentence in the pdf. 

## Checklist
- [x] I have written or updated vitests for this work
- [x] I have reviewed the [accessibility guidelines](https://digital.gov.bc.ca/wcag/home/) relevant to this work
- [x] I have reviewed this work with at least one screen reader (when applicable)
- [x] I have added/updated any related documentation

### CODE REVIEW

**Review by jbook24 — APPROVED** [review]

**Comment by laurenrevere** [comment]
This looks great, found some small translation issues.

Bigger Ones:
- **Table: 9.10.14.4.-B** has the wrong title
- Should we should cut off the title from the Table 9.10.14.4.-A image.

Smaller Ones:
- Table 9.10.14.4.-A, “table” should be part of the link as well
- 0.35 m2 should have a superscript
- Table 9.10.14.4.-B, or -  the “or” should not be part of the link
- Sentence 9 is missing a period at the end
- Sentence 11 a says “he” instead of “the”

Optional/Questions:
- Area = 0.24(2 x LD - 1.2)2 could have more boldness or be more centered.
- "Area = the maximum area of the unprotected opening, and LD = the limiting distance in metres." These don’t quite match the building code. Is this on purpose?
- Sometimes you put “m” for meter next to its value and sometimes you don’t.

**Comment by wardm89** [comment]
> This looks great, found some small translation issues.
> 
> Bigger Ones:
> 
> * **Table: 9.10.14.4.-B** has the wrong title
> * Should we should cut off the title from the Table 9.10.14.4.-A image.
> 
> Smaller Ones:
> 
> * Table 9.10.14.4.-A, “table” should be part of the link as well
> * 0.35 m2 should have a superscript
> * Table 9.10.14.4.-B, or -  the “or” should not be part of the link
> * Sentence 9 is missing a period at the end
> * Sentence 11 a says “he” instead of “the”
> 
> Optional/Questions:
> 
> * Area = 0.24(2 x LD - 1.2)2 could have more boldness or be more centered.
> * "Area = the maximum area of the unprotected opening, and LD = the limiting distance in metres." These don’t quite match the building code. Is this on purpose?
> * Sometimes you put “m” for meter next to its value and sometimes you don’t.

I addressed most everything except: 
- Table 9.10.14.4.-B, or - the “or” should not be part of the link
    - I tried a few things but honestly have no clue at the moment why the ", or" is included when it's not in the tag...
    - `<building-code-modal reference='v2-db-9.10.14.4.-b'>Table 9.10.14.4.-B</building-code-modal'>, or`
    - *Bug ticket?*
- Should we cut off the title from the Table 9.10.14.4.-A image.
    - Not sure what you mean on this one? I did however add the superscript that was missing
-  Area = 0.24(2 x LD - 1.2)2 could have more boldness or be more centered.
    - I made it more bold rather than having to come up with a way to have custom html/css to account for that.

**Comment by laurenrevere** [comment]
> > This looks great, found some small translation issues.
> > Bigger Ones:
> > 
> > * **Table: 9.10.14.4.-B** has the wrong title
> > * Should we should cut off the title from the Table 9.10.14.4.-A image.
> > 
> > Smaller Ones:
> > 
> > * Table 9.10.14.4.-A, “table” should be part of the link as well
> > * 0.35 m2 should have a superscript
> > * Table 9.10.14.4.-B, or -  the “or” should not be part of the link
> > * Sentence 9 is missing a period at the end
> > * Sentence 11 a says “he” instead of “the”
> > 
> > Optional/Questions:
> > 
> > * Area = 0.24(2 x LD - 1.2)2 could have more boldness or be more centered.
> > * "Area = the maximum area of the unprotected opening, and LD = the limiting distance in metres." These don’t quite match the building code. Is this on purpose?
> > * Sometimes you put “m” for meter next to its value and sometimes you don’t.
> 
> I addressed most everything except:
> 
> * Table 9.10.14.4.-B, or - the “or” should not be part of the link
>   
>   * I tried a few things but honestly have no clue at the moment why the ", or" is included when it's not in the tag...
>   * `<building-code-modal reference='v2-db-9.10.14.4.-b'>Table 9.10.14.4.-B</building-code-modal'>, or`
>   * _Bug ticket?_
> * Should we cut off the title from the Table 9.10.14.4.-A image.
>   
>   * Not sure what you mean on this one? I did however add the superscript that was missing
> * Area = 0.24(2 x LD - 1.2)2 could have more boldness or be more centered.
>   
>   * I made it more bold rather than having to come up with a way to have custom html/css to account for that.

Solid solutions. I'll create a bug ticket for the "or" link. https://hous-bssb.atlassian.net/browse/HOUSNAV-112

 This is what I mean about the 9.10.14.4.-A title. Because it's in the image and in text it shows up twice.
Screenshot 2024-07-09 at 10 02 35 AM

**Review by nicholaslyon-dt — APPROVED** [review]
This looks great. Love the structure and I think the way you're using the Heading element and leaving it up to it to determine it's heading level is great. We'll fixing the styling stuff in the follow up ticket.

**Pull request merged**
